<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="example.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.8.3" />
    <PackageReference Include="Blazorise.Splitter" Version="1.8.3" />
  </ItemGroup>

</Project>
